# 100 numpy exercises
This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100. File automatically generated. See the documentation to update questions/answers/hints programmatically.

# The Following are the Solutions of the 100 numpy exercises

In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)

import numpy as np


In [2]:
#### 2. Print the numpy version and the configuration (★☆☆)

print(np.__version__)
print(np.show_config())


1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Lenovo/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\m

In [3]:
#### 3. Create a null vector of size 10 (★☆☆)

null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#### 4. How to find the memory size of any array (★☆☆)

arr = np.zeros((10, 10))
print(arr.size * arr.itemsize)


800


In [7]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
```bash
python -c "import numpy as np; help(np.add)"
```



SyntaxError: invalid syntax (<ipython-input-7-9bd47debf46a>, line 2)

In [8]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)

vector = np.arange(10, 50)
reversed_vector = vector[::-1]
print(reversed_vector)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)


(array([0, 1, 4], dtype=int64),)


In [14]:
#### 11. Create a 3x3 identity matrix (★☆☆)

identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#### 12. Create a 3x3x3 array with random values (★☆☆)

random_array = np.random.random((3, 3, 3))
print(random_array)


[[[0.6704444  0.1333516  0.44814737]
  [0.70513171 0.59132503 0.98115432]
  [0.37977759 0.28838133 0.39781109]]

 [[0.77095388 0.37606617 0.33069162]
  [0.19562894 0.38725007 0.5090794 ]
  [0.23538378 0.9848207  0.78002919]]

 [[0.19327817 0.01405515 0.10311063]
  [0.43893063 0.24689454 0.36495145]
  [0.25573496 0.72901804 0.52570872]]]


In [16]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

random_array = np.random.random((10, 10))
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


Minimum Value: 0.03204274745490954
Maximum Value: 0.9952159431554569


In [17]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

random_vector = np.random.random(30)
mean_value = np.mean(random_vector)
print("Mean Value:", mean_value)


Mean Value: 0.5344152338862922


In [18]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print(array_2d)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

existing_array = np.ones((3, 3))
new_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print(new_array)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
#### 17. What is the result of the following expression? (★☆☆)

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

In [21]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

matrix = np.diag(1 + np.arange(4), k=-1)
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [22]:
#### 19. Create an 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print(checkerboard_matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

shape_array = np.arange(6 * 7 * 8).reshape(6, 7, 8)
index_100 = np.unravel_index(100, shape_array.shape)
print(index_100)


(1, 5, 4)


In [24]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

checkerboard_matrix = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(checkerboard_matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [25]:
#### 22. Normalize a 5x5 random matrix (★☆☆)

random_matrix = np.random.random((5, 5))
normalized_matrix = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix)
print(normalized_matrix)


[[ 1.66542313  0.93276158 -0.890166    0.61497902 -0.0650472 ]
 [ 0.5590255   0.15790355 -0.94465853 -0.58061178 -0.87148372]
 [ 0.61273277 -1.21849596  0.80499845 -1.51756284  1.08351013]
 [-0.7215008  -0.76055463 -0.59759196 -1.52817347 -1.17179181]
 [-0.37831175  1.59436753  1.10047842  1.59019871  0.52957168]]


In [26]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

color_dtype = np.dtype([("R", np.ubyte, 1),
                       ("G", np.ubyte, 1),
                       ("B", np.ubyte, 1),
                       ("A", np.ubyte, 1)])
print(color_dtype)


[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [27]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

matrix_a = np.random.random((5, 3))
matrix_b = np.random.random((3, 2))
result_matrix = np.dot(matrix_a, matrix_b)
# Alternatively, you can use the @ operator for matrix multiplication:
# result_matrix = matrix_a @ matrix_b
print(result_matrix)


[[1.1426941  0.5520727 ]
 [1.4258519  0.86751148]
 [1.16516889 0.78181879]
 [1.04882644 0.44992883]
 [1.11998002 0.8104691 ]]


In [28]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

array_1d = np.arange(11)
array_1d[(array_1d > 3) & (array_1d < 8)] *= -1
print(array_1d)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [29]:
#### 26. What is the output of the following script? (★☆☆)

# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


In [33]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Legal expressions:
- `Z**Z`
- `2 << Z >> 2`
- `1j*Z`
- `Z/1/1`

Feel free to ask if you have any questions or need further explanation!

SyntaxError: invalid syntax (<ipython-input-33-5941bf3f1c3a>, line 9)

In [38]:
#### 28. What are the results of the following expressions? (★☆☆)

np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)



# Division by zero, which leads to a warning and results in nan
np.array(0) / np.array(0)  # Output: nan

# Floor division by zero, which leads to a warning and results in 0
np.array(0) // np.array(0)  # Output: 0

# Conversion of nan to integer results in -9223372036854775808 (minimum integer value)
# and then converting it back to float results in -9.223372036854776e+18
np.array([np.nan]).astype(int).astype(float)  # Output: array([-9.22337204e+18])

C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  after removing the cwd from sys.path.
C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in true_divide
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in floor_divide
  del sys.path[0]


array([-2.14748365e+09])

In [39]:
#### 29. How to round away from zero a float array? (★☆☆)

float_array = np.random.uniform(-10, 10, 10)
rounded_array = np.round(float_array, 0)
print(rounded_array)


[-6. -5. -3. -4.  2.  7. -7.  5.  3. -2.]


In [40]:
#### 30. How to find common values between two arrays? (★☆☆)

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
print(common_values)


[3 4 5]


In [43]:


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

# Not recommended, as it suppresses all warnings including potential issues
np.seterr(all='ignore')

# Your code here

# Reset to default warning settings
np.seterr(all='raise')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [46]:
#### 32. Is the following expression true? (★☆☆)

np.sqrt(-1) == np.emath.sqrt(-1)



FloatingPointError: invalid value encountered in sqrt

In [47]:
#### 33. How to get the dates of yesterday, today, and tomorrow? (★☆☆)

yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-02-04
Today: 2024-02-05
Tomorrow: 2024-02-06


In [48]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

dates_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates_july_2016)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [49]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

A = np.ones(3)
B = np.ones(3) * 2
np.multiply(np.add(A, B, out=B), -A/2, out=B)
print(B)


[-1.5 -1.5 -1.5]


In [50]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

random_array = np.random.uniform(0, 10, 5)
integer_part_method1 = random_array.astype(int)
integer_part_method2 = np.floor(random_array)
integer_part_method3 = np.ceil(random_array) - 1
integer_part_method4 = np.trunc(random_array)

print("Method 1:", integer_part_method1)
print("Method 2:", integer_part_method2)
print("Method 3:", integer_part_method3)
print("Method 4:", integer_part_method4)


Method 1: [6 7 7 6 2]
Method 2: [6. 7. 7. 6. 2.]
Method 3: [6. 7. 7. 6. 2.]
Method 4: [6. 7. 7. 6. 2.]


In [51]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

matrix = np.zeros((5, 5)) + np.arange(5)
print(matrix)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [52]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

def generator_function():
    for i in range(10):
        yield i

array_from_generator = np.fromiter(generator_function(), dtype=int)
print(array_from_generator)

[0 1 2 3 4 5 6 7 8 9]


In [53]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

vector = np.linspace(0, 1, 12)[1:-1]
print(vector)




[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [54]:
#### 40. Create a random vector of size 10 and sort it (★★☆)

random_vector = np.random.random(10)
sorted_vector = np.sort(random_vector)
print(sorted_vector)


[0.0623599  0.06310546 0.24733288 0.25735539 0.39860757 0.43691544
 0.4729267  0.58869017 0.66997117 0.6816764 ]


In [55]:
#### 41. How to sum a small array faster than np.sum? (★★☆)

small_array = np.arange(10)
sum_faster = np.add.reduce(small_array)
print(sum_faster)


45


In [56]:
#### 42. Consider two random array A and B, check if they are equal (★★☆)

array_A = np.random.random(5)
array_B = np.random.random(5)
are_equal = np.array_equal(array_A, array_B)
print(are_equal)


False


In [57]:

#### 43. Make an array immutable (read-only) (★★☆)

immutable_array = np.zeros(10)
immutable_array.flags.writeable = False
# Trying to modify the array will result in a ValueError
# immutable_array[0] = 1


In [58]:
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

cartesian_coordinates = np.random.random((10, 2))
x, y = cartesian_coordinates[:, 0], cartesian_coordinates[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar_coordinates = np.column_stack((r, theta))
print(polar_coordinates)

[[1.12568459 1.00512812]
 [0.74842052 1.37703825]
 [0.61985839 0.05205167]
 [0.72256294 0.91135194]
 [0.36321781 1.15733636]
 [0.59978589 0.26614976]
 [0.87057599 0.15392499]
 [0.63674924 1.44793571]
 [0.39013401 1.21960448]
 [0.64909389 0.40527649]]


In [59]:
#### 45. Create a random vector of size 10 and replace the maximum value by 0 (★★☆)

random_vector = np.random.random(10)
random_vector[random_vector.argmax()] = 0
print(random_vector)


[0.12342762 0.52874105 0.41911929 0.34343312 0.11757879 0.3523222
 0.21862336 0.51762946 0.55708068 0.        ]


In [60]:
#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

structured_array = np.zeros((5, 5), dtype=[('x', float), ('y', float)])
structured_array['x'], structured_array['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(structured_array)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [61]:
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1/(xi - yj)) (★★☆)

X = np.arange(1, 6)
Y = X + 0.5
Cauchy_matrix = 1 / (X[:, np.newaxis] - Y)
print(Cauchy_matrix)


[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4       ]
 [ 0.4         0.66666667  2.         -2.         -0.66666667]
 [ 0.28571429  0.4         0.66666667  2.         -2.        ]]


In [62]:
#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

for dtype in np.sctypeDict:
    if 'float' in dtype or 'int' in dtype:
        print(f"{dtype}: Min = {np.iinfo(dtype).min}, Max = {np.iinfo(dtype).max}")


TypeError: argument of type 'int' is not iterable

In [63]:
#### 49. How to print all the values of an array? (★★☆)

array = np.arange(20).reshape(4, 5)
np.set_printoptions(threshold=np.inf)
print(array)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [64]:
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

vector = np.random.random(10)
scalar = 0.5
closest_value = vector[np.argmin(np.abs(vector - scalar))]
print(closest_value)


0.47205948543473564


In [66]:
#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

structured_array = np.zeros(10, dtype=[('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])])
print(structured_array)


[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0))]


In [67]:
#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

coordinates = np.random.random((100, 2))
distances = np.linalg.norm(coordinates[:, np.newaxis, :] - coordinates, axis=2)
print(distances)


[[0.         0.10175976 0.15078421 0.80824249 0.37194123 0.55504617
  0.80340036 0.44697557 0.5423586  0.35449897 0.3700326  0.45708704
  0.40530919 0.31831912 0.617443   0.38065737 0.23727295 0.69688056
  0.74264551 0.24170015 0.14157684 0.17778009 0.33238376 0.13485292
  0.17572989 0.37080015 0.28394568 0.42725054 0.22952727 0.19204614
  0.37749386 0.37270103 0.6748209  0.73009883 0.11513348 0.75304191
  0.63782362 0.5975818  0.26005427 0.37193591 0.52093193 0.20285952
  0.24704526 0.66871128 0.33316875 0.86677215 0.10666049 0.51931065
  0.48335671 0.39779886 0.58442712 0.16692099 0.35996396 0.97190866
  0.37500609 0.66973721 0.13589495 0.12122236 0.80822691 0.57951543
  0.92140257 0.61853867 1.00683116 0.49287012 0.52782872 0.50476854
  0.21031277 0.67559272 0.93961496 0.35170295 0.59090375 0.61427483
  0.16257744 0.23970231 0.46748983 0.26218838 0.69261992 0.52425635
  1.08157853 0.95630459 0.17289462 0.32188625 0.76333478 0.56822224
  0.13052425 0.94448329 0.81558986 0.72349527 0.

In [68]:
#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

float_array = np.random.random(10).astype(np.float32)
integer_array = float_array.view(np.int32)
print(integer_array)

[1061020589 1055712906 1060847237 1060482991 1037673659 1063058134
 1062982014 1058774602 1027929492 1063290162]


In [72]:

#### 54. How to read the following file? (★★☆)

# 1, 2, 3, 4, 5
# 6,  ,  , 7, 8
# ,  , 9,10,11 


# Assuming the data is saved in a file named 'data.txt'
data = np.genfromtxt('data.txt', delimiter=',', filling_values=np.nan)
print(data)



OSError: data.txt not found.

In [73]:

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

array = np.array(['a', 'b', 'c'])
for index, value in np.ndenumerate(array):
    print(index, value)


(0,) a
(1,) b
(2,) c


In [74]:
#### 56. Generate a generic 2D Gaussian-like array (★★☆)

x, y = np.meshgrid(np.linspace(-1, 1, 5), np.linspace(-1, 1, 5))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
gaussian_array = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(gaussian_array)


[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


In [75]:
#### 57. How to randomly place p elements in a 2D array? (★★☆)

p = 3
array_2d = np.zeros((5, 5))
np.put(array_2d, np.random.choice(range(5*5), p, replace=False), 1)
print(array_2d)


[[0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [76]:
#### 58. Subtract the mean of each row of a matrix (★★☆)

matrix = np.random.random((3, 3))
mean_subtracted_matrix = matrix - matrix.mean(axis=1, keepdims=True)
print(mean_subtracted_matrix)


[[-0.22909674  0.07484821  0.15424853]
 [ 0.16504008 -0.26858657  0.1035465 ]
 [ 0.12366033 -0.13046376  0.00680343]]


In [77]:
#### 59. How to sort an array by the nth column? (★★☆)

array_2d = np.random.random((3, 3))
n = 1
sorted_array = array_2d[array_2d[:, n].argsort()]
print(sorted_array)


[[0.97346465 0.31992578 0.9874473 ]
 [0.26533134 0.36649811 0.9654544 ]
 [0.35415872 0.42032119 0.81556897]]


In [78]:
#### 60. How to tell if a given 2D array has null columns? (★★☆)

array_2d = np.array([[1, 2, 0], [0, 0, 0], [3, 4, 0]])
has_null_columns = np.any(np.all(array_2d == 0, axis=0))
print(has_null_columns)


True


In [79]:
#### 61. Find the nearest value from a given value in an array (★★☆)

array = np.random.random(10)
given_value = 0.5
nearest_value = array[np.abs(array - given_value).argmin()]
print(nearest_value)


0.522468191843241


In [80]:
#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

array1 = np.arange(3).reshape(1, 3)
array2 = np.arange(3).reshape(3, 1)
iterator = np.nditer([array1, array2, None])
for a, b, c in iterator:
    c[...] = a + b
print(iterator.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [81]:

#### 63. Create an array class that has a name attribute (★★☆)

class NamedArray(np.ndarray):
    def __new__(cls, array, name=""):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

named_array = NamedArray(np.arange(5), name="example_array")
print(named_array)
print(named_array.name)

[0 1 2 3 4]
example_array


In [82]:

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

vector = np.ones(10)
indices = np.random.randint(0, len(vector), 5)
np.add.at(vector, indices, 1)
print(vector)


[1. 3. 2. 1. 1. 2. 1. 1. 2. 1.]


In [83]:
#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

X = np.array([1, 2, 3, 4, 5, 6])
I = np.array([1, 3, 9, 3, 4, 1])
F = np.bincount(I, weights=X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [84]:

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

image = np.random.randint(0, 256, (10, 10, 3), dtype=np.ubyte)
unique_colors = len(np.unique(image.reshape(-1, 3), axis=0))
print(unique_colors)

100


In [85]:
#### 67. Considering a four dimensions array, how to get the sum over the last two axes at once? (★★★)

four_dimensions_array = np.random.random((2, 3, 4, 5))
sum_last_two_axes = np.sum(four_dimensions_array, axis=(-2, -1))
print(sum_last_two_axes)

[[ 9.12347855  9.87012443 11.21831968]
 [ 7.40856586 10.0942098   8.95779242]]


In [86]:

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of the same size describing subset indices? (★★★)

D = np.random.random(10)
S = np.random.randint(0, 3, 10)
means = np.bincount(S, weights=D) / np.bincount(S)
print(means)

[0.63590823 0.51929897 0.3563862 ]


In [87]:
#### 69. How to get the diagonal of a dot product? (★★★)

A = np.random.random((3, 3))
B = np.random.random((3, 3))
dot_product_diagonal = np.diag(np.dot(A, B))
print(dot_product_diagonal)


[0.4814453  0.16660685 1.00032105]


In [88]:
#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

original_vector = np.array([1, 2, 3, 4, 5])
new_vector = np.zeros(len(original_vector) + 3 * (len(original_vector) - 1))
new_vector[::4] = original_vector
print(new_vector)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [89]:
#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

array_3d = np.random.random((5, 5, 3))
array_2d = np.random.random((5, 5))
result = array_3d * array_2d[:, :, np.newaxis]
print(result)

[[[4.07795475e-01 4.18687309e-01 2.75068245e-01]
  [1.43872908e-02 5.48526473e-02 9.47669904e-02]
  [6.41010418e-01 1.97465263e-01 3.04528187e-01]
  [2.24545441e-04 2.17991106e-04 1.14481770e-03]
  [5.66188692e-02 2.42298634e-02 3.27661863e-02]]

 [[4.65121412e-01 1.36507955e-01 3.89387659e-02]
  [3.23814658e-02 6.04476728e-02 3.32612917e-02]
  [2.72996090e-02 1.34487617e-01 3.27636264e-02]
  [3.00335668e-01 3.39583248e-01 1.94339930e-01]
  [1.30757284e-02 7.39661152e-02 3.20113540e-03]]

 [[4.87591315e-01 4.43888526e-01 2.01049103e-01]
  [2.72079314e-01 4.27007143e-01 3.82376213e-01]
  [5.40521117e-01 4.14458739e-02 1.79466716e-01]
  [3.99131378e-01 4.07761253e-01 5.96646504e-01]
  [4.49344623e-02 9.28551967e-02 4.28399437e-01]]

 [[1.36244688e-01 4.11188077e-01 6.32115110e-02]
  [1.96009852e-02 1.39165041e-02 1.61478040e-02]
  [1.90296305e-02 9.64834560e-02 1.22826145e-01]
  [2.04182612e-01 3.62739684e-01 5.02294988e-01]
  [1.81502282e-01 5.44039161e-02 9.24552860e-02]]

 [[1.6099228

In [90]:
#### 72. How to swap two rows of an array? (★★★)

matrix = np.random.random((3, 3))
matrix[[0, 1]] = matrix[[1, 0]]
print(matrix)


[[0.51014704 0.17561896 0.39761551]
 [0.69972386 0.55850053 0.55444268]
 [0.84503549 0.74572203 0.77401391]]


In [91]:
#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

triangles = np.random.randint(0, 100, (10, 3))
lines = np.roll(triangles.repeat(2, axis=1), -1, axis=1)
lines = lines.reshape(-1, 2)
unique_lines = np.unique(lines, axis=0)
print(unique_lines)


[[ 9 85]
 [11 13]
 [11 19]
 [13 44]
 [19 35]
 [20 85]
 [35 11]
 [38 73]
 [44 11]
 [50 58]
 [51 70]
 [54  9]
 [54 73]
 [57 85]
 [58 54]
 [58 88]
 [61 57]
 [70 98]
 [73 58]
 [73 95]
 [81 97]
 [85 54]
 [85 61]
 [85 92]
 [88 50]
 [92 20]
 [95 38]
 [97 98]
 [98 51]
 [98 81]]


In [92]:
#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)
print(A)


[1 1 2 3 4 4 6]


In [93]:
#### 75. How to compute averages using a sliding window over an array? (★★★)

array = np.arange(10)
window_size = 3
averages = np.convolve(array, np.ones(window_size)/window_size, mode='valid')
print(averages)


[1. 2. 3. 4. 5. 6. 7. 8.]


In [94]:
#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])) (★★★)

Z = np.arange(10)
shifted_matrix = np.lib.stride_tricks.sliding_window_view(Z, (3,))
print(shifted_matrix)


AttributeError: module 'numpy.lib.stride_tricks' has no attribute 'sliding_window_view'

In [95]:
#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
boolean_array = np.random.choice([True, False], 10)
np.logical_not(boolean_array, out=boolean_array)
print(boolean_array)

float_array = np.random.random(5)
np.negative(float_array, out=float_array)
print(float_array)

[False False  True False  True  True False False False  True]
[-0.63534572 -0.03499553 -0.06211414 -0.03657955 -0.82263311]


In [96]:
#### 78. Consider 2 sets of points P0, P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

P0 = np.random.random((5, 2))
P1 = np.random.random((5, 2))
p = np.random.random(2)
distances = np.abs(np.cross(P1 - P0, P0 - p) / np.linalg.norm(P1 - P0, axis=1))
print(distances)


[0.72974971 0.52094281 0.56657654 0.39642278 0.94715339]


In [97]:
#### 79. Consider 2 sets of points P0, P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i], P1[i])? (★★★)

P0 = np.random.random((5, 2))
P1 = np.random.random((5, 2))
P = np.random.random((3, 2))
distances = np.abs(np.cross(P1[:, np.newaxis] - P0[:, np.newaxis], P0[:, np.newaxis] - P) / np.linalg.norm(P1[:, np.newaxis] - P0[:, np.newaxis], axis=2))
print(distances)

[[0.03235407 0.06095457 0.18571324]
 [0.42924581 0.78922805 0.82454827]
 [0.38169422 0.58265455 0.73427332]
 [0.22090648 0.16446527 0.05442582]
 [0.02143495 0.37750006 0.41659627]]


In [98]:
#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

def extract_subpart(array, shape, position, fill=0):
    r, c = position
    s1, s2 = shape
    result = np.full(shape, fill)
    result[:min(s1, array.shape[0]-r), :min(s2, array.shape[1]-c)] = array[max(0, r-s1//2):r+s1//2+1, max(0, c-s2//2):c+s2//2+1]
    return result

array = np.random.random((10, 10))
subpart = extract_subpart(array, (3, 3), (5, 5), fill=0)
print(subpart)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [99]:
#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

Z = np.arange(1, 15)
R = np.lib.stride_tricks.sliding_window_view(Z, (4,))
print(R)


AttributeError: module 'numpy.lib.stride_tricks' has no attribute 'sliding_window_view'

In [100]:
### 82. Compute a matrix rank (★★★)

matrix = np.random.random((4, 4))
rank = np.linalg.matrix_rank(matrix)
print(rank)


4


In [101]:
#### 83. How to find the most frequent value in an array?

array = np.random.randint(0, 

10, 20)
most_frequent_value = np.bincount(array).argmax()
print(most_frequent_value)


0


In [102]:
#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

matrix = np.random.random((10, 10))
contiguous_blocks = np.lib.stride_tricks.sliding_window_view(matrix, (3, 3))
print(contiguous_blocks)


AttributeError: module 'numpy.lib.stride_tricks' has no attribute 'sliding_window_view'

In [103]:
#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(SymmetricArray, self).__setitem__((i, j), value)
        super(SymmetricArray, self).__setitem__((j, i), value)

symmetric_array = SymmetricArray(np.zeros((5, 5)))
symmetric_array[0, 1] = 1
print(symmetric_array)
print(symmetric_array[1, 0])


TypeError: only integer scalar arrays can be converted to a scalar index

In [104]:
#### 86. Consider a set of p matrices with shape (n, n) and a set of p vectors with shape (n, 1). How to compute the sum of the p matrix products at once? (result has shape (n, 1)) (★★★)

p = 3
matrices = [np.random.random((4, 4)) for _ in range(p)]
vectors = [np.random.random((4, 1)) for _ in range(p)]
result = sum(np.dot(matrix, vector) for matrix, vector in zip(matrices, vectors))
print(result)



[[2.97056448]
 [3.25853301]
 [3.22511335]
 [3.31037047]]


C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  


In [105]:

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

array = np.random.random((16, 16))
block_sum = np.sum(np.lib.stride_tricks.sliding_window_view(array, (4, 4)), axis=(-2, -1))
print(block_sum)


AttributeError: module 'numpy.lib.stride_tricks' has no attribute 'sliding_window_view'

In [106]:
#### 88. How to implement the Game of Life using numpy arrays? (★★★)

def game_of_life(board, steps):
    for _ in range(steps):
        neighbor_count = sum(np.roll(np.roll(board, i, 0), j, 1) for i in (-1, 0, 1) for j in (-1, 0, 1) if (i, j) != (0, 0))
        board = ((board == 1) & (neighbor_count == 3)) | ((board == 0) & (neighbor_count == 2))
    return board

initial_board = np.random.choice([0, 1], (50, 50))
final_board = game_of_life(initial_board, 100)
print(final_board)


[[False False False  True False  True False False False False False False
   True  True  True  True False  True False  True  True False False  True
  False  True False False False False False  True False False False False
  False False False False False  True False False  True False False  True
   True False]
 [ True False False  True False False False  True False False False  True
   True False False False False False  True  True False False  True False
  False False False  True False False False False False False  True  True
  False  True  True False False  True False False  True False  True False
   True  True]
 [False False  True False  True False False False False False False False
  False False False False False False False False False False False False
  False False False False False  True False False  True  True False False
  False  True  True False False False False False False  True False  True
  False False]
 [False False False  True False False False  True False  True False

C:\Users\Lenovo\anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  """


In [107]:
### 89. How to get the n largest values of an array (★★★)
n
array = np.random.random(10)
n_largest_values = array[np.argsort(array)[-n:]][::-1]
print(n_largest_values)


[0.75672868]


In [108]:
#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

vectors = [np.array([1, 2]), np.array([3, 4, 5]), np.array([6, 7])]
cartesian_product = np.array(np.meshgrid(*vectors)).T.reshape(-1, len(vectors))
print(cartesian_product)


[[1 3 6]
 [1 4 6]
 [1 5 6]
 [2 3 6]
 [2 4 6]
 [2 5 6]
 [1 3 7]
 [1 4 7]
 [1 5 7]
 [2 3 7]
 [2 4 7]
 [2 5 7]]


In [109]:
#### 91. How to create a record array from a regular array? (★★★)

regular_array = np.array([(1, 2, 3), (4, 5, 6)], dtype=[('a', int), ('b', int), ('c', int)])
record_array = np.core.records.fromarrays(regular_array.T, dtype=[('a', int), ('b', int), ('c', int)])
print(record_array)


ValueError: mismatch between the number of fields and the number of arrays

In [110]:
### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

Z = np.random.random(10**6)
power_3_method1 = np.power(Z, 3)
power_3_method2 = Z * Z * Z
power_3_method3 = np.einsum('i,i,i->i', Z, Z, Z)
print(np.allclose(power_3_method1, power_3_method2, power_3_method3))


True


In [111]:
#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

A = np.random.randint(0, 10, (8, 3))
B = np.random.randint(0, 10, (2, 2))
rows_containing_elements = np.all(np.isin(A, B), axis=1)
print(A[rows_containing_elements])


[]


In [113]:

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g


matrix = np.random.randint(0, 3, (10, 3))
rows_with_unequal_values = np.any(np.diff(matrix, axis=1) != 0, axis=1)
print(matrix[rows_with_unequal_values])


[[1 0 2]
 [0 2 2]
 [2 1 2]
 [0 1 1]
 [2 1 1]
 [1 2 0]
 [1 1 0]
 [2 0 1]
 [1 2 0]
 [0 0 1]]


In [114]:

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

vector = np.array([0, 1, 2, 3], dtype=np.uint8)
binary_representation = ((vector[:, None] & (1 << np.arange(8))) > 0).astype(int)
print(binary_representation)


[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]]


In [115]:

#### 96. Given a two-dimensional array, how to extract unique rows? (★★★)

array_2d = np.random.randint(0, 2, (5, 3))
unique_rows = np.unique(array_2d, axis=0)
print(unique_rows)


[[0 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [116]:

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
inner_product = np.einsum('i,i->', A, B)
outer_product = np.einsum('i,j->ij', A, B)
sum_result = np.einsum('i->', A)
elementwise_multiply = np.einsum('i,i->i', A, B)
print(inner_product, outer_product, sum_result, elementwise_multiply)


32 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]] 6 [ 4 10 18]


In [119]:
#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

X = np.array([1, 2, 3, 4, 5])
Y = np.array([2, 3, 4, 5, 6])
path_length = np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))
equidistant_samples = np.interp(np.linspace(0, path_length[-1], 10), path_length, X)
print(equidistant_samples)


ValueError: fp and xp are not of the same length.

In [120]:

#### 99. Given an integer n and a 2D array X, select from X the rows that can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

n = 5
X = np.array([[1, 2, 2], [0, 3, 2], [1, 1, 3], [5, 0, 0]])
valid_rows = np.all(X == X.astype(int), axis=1) & (np.sum(X, axis=1) == n)
selected_rows = X[valid_rows]
print(selected_rows)

[[1 2 2]
 [0 3 2]
 [1 1 3]
 [5 0 0]]


In [121]:
#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

X = np.random.random(100)
N = 1000
bootstrapped_means = np.random.choice(X, (N, len(X)), replace=True).mean(axis=1)
confidence_interval = np.percentile(bootstrapped_means, [2.5, 97.5])
print(confidence_interval)

[0.4483946  0.56765414]
